apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: xnylesx/ticketing:auth
          env:
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
