apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: auth
          image: xnylesx/ticketing:client
          env:
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
