apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/path-regex: "case_insensitive"
spec:
  ingressClassName: nginx
  rules:
    - host: https://4a4bcd4c-0e87-48cc-9fae-14901d14f306.k8s.ondigitalocean.com
      http:
        paths:
          - path: /api/users/[A-Z0-9]
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000
